#!/usr/bin/env bash
# this script will display a message and then sleep. This lifecycle will never end
x=1
trap 'echo "I am invincible!!!"' sigterm
while [ $x -lt 2 ]
do
	echo "To infinity and beyond"
	sleep 2
done
