#!/usr/bin/env bash
# This script will display the desired message but on the 9th time it will display an additional message. After 11 messages the script will stop.
n=1
while [ $n -le 10 ]
do
	echo "Best School"
	
	if [ $n -eq 9 ]
	then
		printf "Hi\n"
		n=$(( n + 1 ))
	else
		n=$(( n + 1 ))
	fi
done
