#!/usr/bin/env bash
# while | display every minute between 1 and 59 | display hours from 0 to 12
hour=0
minute=0
while [ $hour -le 12 ]
do
	printf "%s\n" "Hour: $hour"
		while [ $minute -le 59 ]
		do
			printf "%s\n" "$minute"
			minute=$(( minute + 1 ))
		done
	(( minute = 1))
	hour=$(( hour + 1 ))
done
