#!/usr/bin/env bash
# this script checks the hour and then if it is less than or equal to 12 it prints the hour, while that is happening it will print the minute as long as it is less than 59. 
hour=0
minute=1
while [ $hour -le 12 ]
do
	printf "%s\n" "Hour: $hour"
		while [ $minute -le 59 ]
		do
			printf "%s\n" "$minute"
			minute=$(( minute + 1 ))
		done
	(( minute = 1))
	hour=$(( hour + 1 ))
done
