#!/usr/bin/env bash
# this script first checks to see if the file does not exist and is not a directory. if both are true it displays that the file does not exist and exits the script. Then if the file exists and has content the script will say so, and then if it is a regular file it will display that as well.

F=./school
if [ ! -f "$F" ] && [ ! -d "$F" ]; then
	echo "school file does not exist"
	exit 1
elif
	[ -s "$F" ]; then
	printf "school file exists\nschool file is not empty\n"
elif
	[ ! -s "$F" ]; then
	printf "school file exists\nschool file is empty\n"
else
	printf ""
fi

if [ -f "$F" ]; then
	printf "school is a regular file\n"
else
	printf ""
fi
